### ISSUE TITLE
Game crashing constantly

### ISSUE THREAD

**Issue by DejFidOFF** [TaskaRaine/Gifty#1]
Game: VS 1.20pre9
Gifty: 1.0.0rc3

In creative take box, place at floor, add lid. Gift completed. Click on that with middle mouse button to get it whole. gift end in the inventory and start constantly crushed. Right after connected to the server. Or in survival make a gift box with the lid. Break a block. Game crushed right after you pick the whole gift box to inventory.

LOG:
Running on 64 bit Windows 10.0.22631.0 with 81842 MB RAM
Game Version: v1.20.0-pre.9 (Unstable)
31.10.2024 7:55:16: Critical error occurred in the following mod: gifty@1.0.0-rc.3
Loaded Mods: aged@1.0.5, ClaimsRadar@1.1.0, domesticanimaltrader@1.0.2, dinornithidae@1.0.2, sirenia@1.0.8, largercrock@1.0.2, mushroomtrader@1.0.2, primitivesurvival@3.7.0, translocatorengineeringredux@1.5.4, game@1.20.0-pre.9, wildanimalstrader@1.0.3, carryon@1.8.0-pre.1, extrainfo@1.8.1, gifty@1.0.0-rc.3, hydrateordiedrate@1.4.8-pre.7, playerlist@2.1.4, creative@1.20.0-pre.9, vsserverpanel@0.1.5, survival@1.20.0-pre.9, wildfarmingrevival@1.2.9, shearlib@1.0.1, wool@1.2.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gifty.Blocks.BlockGiftBox.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in C:\Projects\VintageStory\Mods\gifty\src\blocks\BlockGiftBox.cs:line 96
   at Vintagestory.API.Common.ItemStack.GetDescription(IWorldAccessor world, ItemSlot inSlot, Boolean debug) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 401
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 476
   at Vintagestory.Client.NoObf.HudMouseTools.OnRequireInfoText(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 167
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose() in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 125
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 211
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 516
   at Vintagestory.Client.NoObf.InputAPI.TriggerOnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\API\InputAPI.cs:line 48
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 881
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 514
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 598
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 439
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2016
   at Vintagestory.Client.GuiScreenRunningGame.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 347
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 328
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 30.10.2024 23:23:22, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x8b78
Čas spuštění chybující aplikace: 0x0x1db2b1a1c3623b3
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 9ae742e6-80aa-4d79-84c5-f1aaf6b8d549
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 30.10.2024 12:26:33, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x84dc
Čas spuštění chybující aplikace: 0x0x1db2abe69a3f915
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: b41d698d-8e08-43b5-bff3-09b3631ee7df
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 26.10.2024 15:33:06, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x4868
Čas spuštění chybující aplikace: 0x0x1db27ab7ae32b8f
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 7522ac9e-6480-48ec-9c35-3a72fc1a03b3
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by TaskaRaine** [comment]
I've managed to recreate these, I think, and have solved them. There seem to be some further issues with giftboxes retaining their contents, too, so I'm going to try and solve that before putting out a fix
